name: Copy DOC to DSL

# Указываем, когда workflow должен запускаться
on:
  push:
    branches:
      - master  # Запускать только при изменении в ветке master

jobs:
  copy:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий DOC
      - name: Checkout DOC
        uses: actions/checkout@v3

      # Шаг 2: Клонируем репозиторий DSL
      - name: Clone DSL
        run: |
          git clone "pangea-gh:NikiTikkiTavisai/Test-git-reset-Workspace-DSL.git"

      # Шаг 3: Копируем содержимое DOC в папку doc репозитория DSL
      - name: Copy DOC to DSL/doc
        run: |
          mkdir -p Test-git-reset-Workspace-DSL/doc  # Создаем папку doc, если её нет
          cp -r * Test-git-reset-Workspace-DSL/doc/  # Копируем всё содержимое DOC в DSL/doc
          cd Test-git-reset-Workspace-DSL

      # Шаг 4: Настраиваем Git для фиксации изменений
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Шаг 5: Фиксируем изменения и отправляем их в репозиторий DSL
      - name: Commit and Push changes to DSL
        run: |
          cd Test-git-reset-Workspace-DSL
          git add .
          git commit -m "Автоматическое обновление DOC из репозитория Test--doc"
          git push "pangea-gh:NikiTikkiTavisai/Test-git-reset-Workspace-DSL.git" master